name: Deploy Cloud Functions (test)
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  call-reusable-deploy:
    uses: ./.github/workflows/reusable-deploy-cloud-function.yaml
    with:
      function_name: 'line-ai-bot-test'
      project_id: 'nobu5-393106'
      region: 'us-west1'
      service_account_email: 'cloud-run-functions-deployer@nobu5-393106.iam.gserviceaccount.com'
      workload_identity_provider: 'projects/1035100650942/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider'
      deploy_http_trigger: true
      deploy_event_trigger: true
      secrets_config: |-
        OPENAI_KEY_LINE_AI_BOT=projects/nobu5-393106/secrets/OPENAI_KEY_LINE_AI_BOT/versions/latest
        LINE_TOKENS_N_TARGETS=projects/nobu5-393106/secrets/LINE_TOKENS_N_TARGETS/versions/latest
        FIREBASE_CONFIG=projects/nobu5-393106/secrets/FIREBASE_CONFIG/versions/latest
    # Secrets are passed via inputs.secrets_config
