- name: Deploy to Cloud Functions
  uses: google-github-actions/deploy-cloud-functions@v2
  with:
    name: 'line-ai-bot-test'
    region: 'us-west1'
    runtime: 'php82' # 例: ランタイム
    entry_point: 'main'
    source: '.'
