name: Deploy Cloud Functions (test)
on:
  push:
    branches:
      - test
  workflow_dispatch:

jobs:
  call-reusable-deploy:
    uses: ./.github/workflows/reusable-deploy-cloud-function.yaml
    with:
      function_name: 'line-ai-bot-test' # Test-specific function name
      project_id: 'nobu5-393106'
      region: 'us-west1'
      service_account_name: 'cloud-run-functions-deployer'
      gcp_project_number: '1035100650942'
      wip_pool_name: 'github-actions-pool'
      wip_provider_name: 'github-provider'
      secrets_project_id: 'nobu5-393106'
      secrets_config: |-
        OPENAI_KEY_LINE_AI_BOT
        LINE_TOKENS_N_TARGETS
        FIREBASE_CONFIG
      # Other inputs use defaults from callable workflow
