name: Deploy Cloud Functions (production)
on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

env:
  PROJECT_ID: nobu5-393106
  FUNCTION_NAME: line-ai-bot
  REGION: us-west1

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Google Cloud認証
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/1035100650942/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider'
          service_account: 'cloud-run-functions-deployer@nobu5-393106.iam.gserviceaccount.com'

      - name: Deploy Cloud Functions (http)
        uses: 'google-github-actions/deploy-cloud-functions@v3'
        timeout-minutes: 5
        with:
          name: ${{ env.FUNCTION_NAME }}
          runtime: php82
          entry_point: main
          region: ${{ env.REGION }}
          service_account: 'cloud-run-functions-deployer@nobu5-393106.iam.gserviceaccount.com'
          source_dir: ./
          max_instance_count: 1
          secrets: |-
            OPENAI_KEY_LINE_AI_BOT=projects/nobu5-393106/secrets/OPENAI_KEY_LINE_AI_BOT/versions/latest
            LINE_TOKENS_N_TARGETS=projects/nobu5-393106/secrets/LINE_TOKENS_N_TARGETS/versions/latest
            FIREBASE_CONFIG=projects/nobu5-393106/secrets/FIREBASE_CONFIG/versions/latest

      - name: Deploy Cloud Functions (event)
        uses: 'google-github-actions/deploy-cloud-functions@v3'
        timeout-minutes: 5
        with:
          name: ${{ env.FUNCTION_NAME }}-trigger
          runtime: php82
          entry_point: trigger
          event_trigger_pubsub_topic: ${{ env.FUNCTION_NAME }}-trigger
          region: ${{ env.REGION }}
          service_account: 'cloud-run-functions-deployer@nobu5-393106.iam.gserviceaccount.com'
          source_dir: ./
          max_instance_count: 1
          secrets: |-
            OPENAI_KEY_LINE_AI_BOT=projects/nobu5-393106/secrets/OPENAI_KEY_LINE_AI_BOT/versions/latest
            LINE_TOKENS_N_TARGETS=projects/nobu5-393106/secrets/LINE_TOKENS_N_TARGETS/versions/latest
            FIREBASE_CONFIG=projects/nobu5-393106/secrets/FIREBASE_CONFIG/versions/latest
