name: Deploy Cloud Functions (2nd Gen)

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: nobu5-393106 # Google Cloud プロジェクト ID
  FUNCTION_NAME: line-ai-bot-test # デプロイするCloud Functions関数の名前
  REGION: us-west1 # 関数をデプロイするリージョン (Cloud Runサービスが起動するリージョン)

permissions:
  contents: 'read'
  id-token: 'write' # OIDC認証のために必要

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Google Cloud認証
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/1035100650942/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider'
          service_account: 'cloud-run-functions-deployer@nobu5-393106.iam.gserviceaccount.com'

      - name: Deploy Cloud Function (2nd Gen)
        uses: 'google-github-actions/deploy-cloud-functions@v1'
        with:
          name: ${{ env.FUNCTION_NAME }}
          runtime: php82 # 例: nodejs20, python311, go121 など、関数のランタイム
          entry_point: main # 関数のエントリポイント (例: `helloHttp`, `myHandler` など)
          source_dir: ./ # 関数コードがあるディレクトリ
          region: ${{ env.REGION }}
          trigger_http: true # HTTPトリガーの場合
          # trigger_topic: my-pubsub-topic # Pub/Subトリガーの場合
          # event_trigger_type: google.cloud.pubsub.topic.v1.messagePublished # Pub/Subトリガーの場合
          # event_trigger_resource: projects/${{ env.PROJECT_ID }}/topics/my-pubsub-topic # Pub/Subトリガーの場合
          gen2: true # これが第2世代であることを明示的に示す重要なオプション
          # service_account_email: [FUNCTION_RUNTIME_SA_EMAIL] # 関数が実行時に利用するサービスアカウント
