name: Reusable Deploy Cloud Function

on:
  workflow_call:
    inputs:
      function_name:
        description: 'Cloud Function の名前'
        required: true
        type: string
      project_id:
        description: '関数をデプロイする Google Cloud プロジェクトID'
        required: true
        type: string
      region:
        description: '関数を配置する Google Cloud リージョン'
        required: true
        type: string
      service_account_name:
        description: 'サービスアカウント名（例: my-sa-name）'
        required: true
        type: string
      gcp_project_number:
        description: 'Google Cloud プロジェクト番号（Workload Identity 用）'
        required: true
        type: string
      wip_pool_name:
        description: 'Workload Identity プール名'
        required: false
        type: string
        default: 'github-actions-pool'
      wip_provider_name:
        description: 'Workload Identity プロバイダー名'
        required: false
        type: string
        default: 'github-provider'
      secrets_project_id:
        description: 'シークレットが格納されている Google Cloud プロジェクトID（未指定時は function の project_id を使用）'
        required: false
        type: string
      secrets_config:
        description: 'シークレット名の複数行文字列（例: "SECRET_A\nSECRET_B"）'
        required: true
        type: string
      runtime:
        description: 'Cloud Function のランタイム（例: php82）'
        required: false
        type: string
        default: 'php82'
      source_dir:
        description: '関数コードのソースディレクトリ'
        required: false
        type: string
        default: './'
      max_instance_count:
        description: '関数の最大インスタンス数'
        required: false
        type: number
        default: 1
      deploy_http_trigger:
        description: 'HTTP トリガー関数をデプロイするかどうか'
        required: false
        type: boolean
        default: true
      http_entry_point:
        description: 'HTTP トリガー関数のエントリポイント'
        required: false
        type: string
        default: 'main'
      deploy_event_trigger:
        description: 'イベントトリガー関数をデプロイするかどうか'
        required: false
        type: boolean
        default: true
      event_entry_point:
        description: 'イベントトリガー関数のエントリポイント'
        required: false
        type: string
        default: 'trigger'
      event_trigger_pubsub_topic_suffix:
        description: 'イベントトリガー Pub/Sub トピックのサフィックス（function_name に付加されます）'
        required: false
        type: string
        default: '-trigger'
    secrets:
      pass: ""
