name: Run test for line-ai-bot

# env:
#   target: line-ai-bot

on:
  pull_request:
    types: [opened, reopened, synchronize]
    # paths:
    #   - 'line-ai-bot/**'
    #   - '.github/workflows/test-line-ai-bot.yml'
  push:
    branches: main
    # paths:
    #   - 'line-ai-bot/**'
    #   - '.github/workflows/test-line-ai-bot.yml'
  schedule:
    - cron:  '55 21 * * 5'
  workflow_dispatch:

# defaults:
#   run:
#     working-directory: .

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Set up PHP 8.2
      uses: shivammathur/setup-php@v2
      with:
        php-version: "8.2"
        extensions: grpc

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Get current directory
      id: current_dir
      run: echo "CURRENT_DIR=$(pwd)" >> $GITHUB_OUTPUT

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v4
      with:
        path: ${{ steps.current_dir.outputs.CURRENT_DIR }}/vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Put firebase config
      uses: ./_cf-common/.github/actions/put_firebase_config
      with:
        COMMON_FIREBASE_BASE64: ${{ secrets.COMMON_FIREBASE_BASE64 }}

    - name: Create /configs
      env:
        DECODED_BASE64: ${{ secrets.GPT_BASE64 }}
      run: |
        echo $DECODED_BASE64 | base64 --decode > configs/gpt.json

    - name: Test with phpunit
      run: |
        bash tests/run_tests.sh
